name: Login in to Docker Hub account and push image
description: Login to Docker Hub

inputs:
  docker_username:
    description: "Defines your Docker username"
    required: true
    default: "gustavomelo960"
  image_name:
    description: "Tag the current image with the docker username"
    required: true
    default: $NAME:$TAG

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag image
      shell: bash
      run: docker tag ${{inputs.image_name}} ${{inputs.docker_username}}/dockeracademy:$TAG

    - name: Push image to Docker Hub
      shell: bash
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/dockeracademy:$TAG
